#!/usr/bin/env python3
"""Split FRONTIER Act (H.R. ll, Obernolte-Trahan, introduced 2026-07-23) into
per-section markdown files. Parallel to `split_gaaia.py` in this directory but
much simpler because FRONTIER is a flat 9-section bill (no titles/subtitles,
no amendments-to-other-acts complications). Emits sections/sec-N-slug.md files
each carrying:

  - HTML-comment header pointing back to bill source + line range
  - Fenced block containing the raw pdftotext output for that section

Also emits SECTION_MANIFEST.md at bill dir root.

Note on format: this script uses a different section-file format than
`split_gaaia.py` (which uses visible provenance bullets + a `text` fence
language tag, per the committed GAAIA sections). The two are intentionally
not harmonized — retro-fixing either bill's committed section files is a
separate decision. If you add a new bill's splitter, pick one convention
knowingly.
"""

import re
import sys
from pathlib import Path

BILL_DIR = Path("/Users/dan/code/policy-levers/bills/frontier-act")
SRC_TXT = BILL_DIR / "frontier_act_text.txt"
SECTIONS_DIR = BILL_DIR / "sections"
MANIFEST = BILL_DIR / "SECTION_MANIFEST.md"

# Filename slugs — hand-curated because SEC. headers wrap awkwardly across lines
# (§§ 7 and 8 have multi-line titles). Titles below reflect the full statutory
# title once the wrap is reconstructed.
SECTION_META = [
    (0, 1,  "Short title",                                                "short-title"),
    (1, 2,  "Definitions",                                                "definitions"),
    (2, 3,  "Rulemaking",                                                 "rulemaking"),
    (3, 4,  "Transparency and reporting",                                 "transparency-and-reporting"),
    (4, 5,  "Independent verification",                                   "independent-verification"),
    (5, 6,  "Cumulative obligations",                                     "cumulative-obligations"),
    (6, 7,  "Government Accountability Office report on the market for "
            "independent verification organizations",                     "gao-report-on-ivo-market"),
    (7, 8,  "Emergency orders addressing imminent catastrophic risk",     "emergency-orders-imminent-catastrophic-risk"),
    (8, 9,  "Relationship to State laws",                                 "relationship-to-state-laws"),
]

def find_boundaries(lines):
    """Return list of (start_line_1indexed, sec_num) for each top-level SEC."""
    starts = []
    # Section 1 uses "SECTION 1." per bill drafting convention.
    sec1_re = re.compile(r"^\s{5,}\d+\s+SECTION 1\.")
    # Sections 2+ use "SEC. N." (single leading number, top-level, indented).
    secN_re = re.compile(r"^\s{5,}\d+\s+SEC\. (\d+)\.")
    for i, line in enumerate(lines, start=1):
        if sec1_re.match(line):
            starts.append((i, 1))
            continue
        m = secN_re.match(line)
        if m:
            starts.append((i, int(m.group(1))))
    return starts

def main():
    if not SRC_TXT.exists():
        sys.exit(f"ERROR: {SRC_TXT} missing — run pdftotext first")
    # Use split("\n") not splitlines(): pdftotext page breaks insert form-feed /
    # vertical-tab characters that splitlines() treats as line boundaries but
    # grep/Read/cat -n do not, which desynchronizes the manifest line numbers
    # from what a human sees with those tools.
    lines = SRC_TXT.read_text(encoding="utf-8").split("\n")
    total_lines = len(lines)

    boundaries = find_boundaries(lines)
    if len(boundaries) != 9:
        sys.exit(f"ERROR: expected 9 SEC boundaries, found {len(boundaries)}: {boundaries}")

    # Sanity-check numbers 1..9 in order.
    expected = list(range(1, 10))
    got = [n for _, n in boundaries]
    if got != expected:
        sys.exit(f"ERROR: SEC numbers off — got {got}, expected {expected}")

    SECTIONS_DIR.mkdir(parents=True, exist_ok=True)

    manifest_rows = ["# FRONTIER Act — section manifest",
                     "",
                     "Auto-generated by /tmp/split_frontier.py. Do not hand-edit.",
                     "",
                     "| # | Num | Title | Source lines | File |",
                     "|---|---|---|---|---|"]

    for idx, (start_1, sec_num) in enumerate(boundaries):
        end_1 = boundaries[idx + 1][0] - 1 if idx + 1 < len(boundaries) else total_lines
        # Locate metadata by ordinal (we verified 1..9 sequential above)
        _, _, full_title, slug = SECTION_META[idx]
        fname = f"sec-{sec_num}-{slug}.md"
        # Extract raw body — inclusive of header, exclusive of next SEC start.
        body = "\n".join(lines[start_1 - 1:end_1])
        out_path = SECTIONS_DIR / fname
        header = (
            f"<!--\n"
            f"Section: SEC. {sec_num}. {full_title.upper()}\n"
            f"Source: bills/frontier-act/frontier_act_text.txt\n"
            f"Lines: {start_1}–{end_1} (inclusive, 1-indexed)\n"
            f"Extracted: 2026-07-24 by /tmp/split_frontier.py\n"
            f"-->\n\n"
            f"# SEC. {sec_num}. {full_title.upper()}\n\n"
            f"```\n"
        )
        out_path.write_text(header + body + "\n```\n", encoding="utf-8")
        manifest_rows.append(
            f"| {idx} | {sec_num} | {full_title.upper()} | {start_1}–{end_1} | `sections/{fname}` |"
        )
        print(f"wrote {out_path.name}  ({end_1 - start_1 + 1} lines)")

    MANIFEST.write_text("\n".join(manifest_rows) + "\n", encoding="utf-8")
    print(f"wrote {MANIFEST}")

if __name__ == "__main__":
    main()
